version: '3'

services:
  # database
  postgres:
    container_name: db
    image: postgres:10.1
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data/
  # admin database
  pgadmin:
    container_name: pgadmin
    image: thajeztah/pgadmin4
    ports:
      - '5050:5050'
    volumes:
      - ./pgadmin:/pgadmin
    depends_on:
      - postgres
  # server
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    links:
    - postgres
    depends_on:
      - postgres
  # web
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: front.dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./frontend:/home/app
    command: "npm run serve"
  # rabbit
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbit
    ports:
      - "15673:15672"
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
  # redis
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"   