# Generated by Django 2.0.1 on 2018-07-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='name_room',
            field=models.CharField(default='chat room', max_length=200),
        ),
    ]
