# Generated by Django 2.0.1 on 2018-07-24 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_name_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsessionmember',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.ChatSession'),
        ),
        migrations.AlterField(
            model_name='chatsessionmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.ChatSession'),
        ),
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
