# Generated by Django 2.0.1 on 2018-07-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180724_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='name_room',
            new_name='room_name',
        ),
    ]
